---
title: "SmarterThanCovid"
resource_files:
- data/gadm36_ZAF_1.shp
- data/gadm36_ZAF_shp/gadm36_ZAF_1.shp
- data/gadm36_ZAF_shp/gadm36_ZAF_1.cpg
- data/gadm36_ZAF_shp/gadm36_ZAF_1.dbf
- data/gadm36_ZAF_shp/gadm36_ZAF_1.prj
- data/gadm36_ZAF_shp/gadm36_ZAF_1.shp
- data/gadm36_ZAF_shp/gadm36_ZAF_1.shx
- data/sa_map/gadm36_ZAF_1.shp
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
    vertical_layout: fill
---




```{r setup, include=FALSE}


# ___________________________________ Install Dependencies & Curate Data ___________________________________
configure_workspace <- function() {
  # Dependencies

  # remotes::install_github("GuangchuangYu/nCov2019")
  library(flexdashboard)
  library(knitr)
  library(shiny)
  library(tidyverse)
  library(coronavirus)
  library(sf)
  library(raster)
  library(htmltab)
  library(tmap)    
  library(leaflet) 
  library(ggplot2) 
  library(maptools)
  library(rvest)
  library(RColorBrewer)
  library(htmlwidgets)
  library(ggrepel)
  library(nCov2019)
  library(chinamap)
  library(plotly)
  library(tidyr)
  library(ggrepel)
  library(rgdal)
  library(sp)
  library(ggspatial)
  library(rsconnect)
  library(readxl)
 # setwd("~/Desktop/covid19")
  
}
get_data <- function() {
  # run to fetch & clean all the data
  
  # ______________________________ South African Data ______________________________
  # provincial data
  province <- c('Western Cape','Eastern Cape','Northern Cape', 'Free State', 'KwaZulu-Natal', 'North West', 
                'Gauteng', 'Mpumalanga', 'Limpopo')
  population <- c(6621103, 6522734, 1225555, 2954348, 11384722, 3978955, 14717040, 4523874, 5797275)
  population_2 <- paste(round(population/1000000, 2), 'm', sep='')
  density <- c(51.1, 38.6, 3.3, 22.8, 120.7, 37.9, 809.6, 59.1, 46.1)
  provincial.data <- data.frame(province, population, population_2, density, stringsAsFactors=FALSE)
  
  # --- Add later ---               # Gender & Age demographics
  Age <- c('0-9', '10-19', '20-29', '30-39', '40-49', '50-59', '60-69', '70-79', '80+')
  Male <- c('5 292 766','4 842 847','5 237 328','3 754 553','2 598 068','1 823 299','1 013 912','458 781','176 237')
  Female <- c('5 212 437', '4 755 516', '5 196 531', '2 751 224', '2 970 834', '2 192 398', '1 329 660', '770 816', '402 352')
  total <- c('10 505 203','9 598 363','10 433 859','6 505 777','5 568 902','4 015 697','2 343 572','1 229 597','419 989' )
  age.data <- data.frame(Age, Male, Female,total, stringsAsFactors=FALSE)
  # --- Add later ---
  
  # Get South African Covid Data
  covid_sa_url <- 'https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_South_Africa'
  covid_sa <<- read_html(covid_sa_url) %>% html_node(xpath='//*[@id="mw-content-text"]/div/table[3]') %>% html_table(fill=T)
  
  # geospatial data
  #south_africa <<- readShapeSpatial('data/gadm36_ZAF_shp/gadm36_ZAF_1.shp')
 # south_africa <<- rgdal::readOGR('data/sa_map_data/SOU-level_1.shp') #rgdal::readOGR('data/gadm36_ZAF_shp/gadm36_ZAF_1.shp')
  
 # south_africa <- rgdal::readOGR('data/sa_map//gadm36_ZAF_1.shp')
  # ______________________________ South African Data ______________________________
  

#  south_africa <<- rgdal::readOGR('data/sa_map/gadm36_ZAF_1.shp')
  
  



  # _________________________________ Concatenate Data _________________________________

  # Extract number of cases
  test <- t(covid_sa[covid_sa$Day=='Cases',3:11])
  test <- data.frame(test[1:nrow(test),])
  colnames(test) <- 'Cases'
  test$Cases <- as.numeric(as.character(test$Cases))
  sa_cases <<- test
  
  # add to dataframe
  #south_africa@data <- cbind(test, south_africa@data)
  
  # province data
#  south_africa@data <<- merge(south_africa@data, provincial.data, by.x='NAME_1', by.y='province')
  
  # _________________________________ Concatenate Data _________________________________
  

  

  
  
  
  
  # _________________________________ Global Data _________________________________
  # global case data
  n_cases <<- load_nCov2019(lang='en')
  
  # median population data
  med_age <<- read.csv('data/median-age.csv')
  
  # clean
  med_age <<- group_by(med_age, Entity) %>% filter(Year==2020) %>%
    transmute(name=factor(Entity),
              code=Code,
              country=Entity,
              median_age=UN.Population.Division..Median.Age...2017...years.)
  
  
  # Global Population Data
  global_population <<- read.csv('./data/global_population.csv')
  
  # _________________________________ Global Data _________________________________
  
  
  
  # _________________________________ Worldometer Data _________________________________
  # Script to scrape summary data from 'https://www.worldometers.info/coronavirus/' and remove commas.
  worldometer_url <- 'https://www.worldometers.info/coronavirus/'
  worldometer <<- read_html(worldometer_url) %>% html_node(xpath='//*[@id="main_table_countries_today"]') %>% html_table(fill=T)
  worldometer$TotalCases <- as.numeric(gsub(",","",worldometer$TotalCases))
  worldometer$NewCases <- as.numeric(gsub(",","",worldometer$NewCases))
  worldometer$TotalDeaths <- as.numeric(gsub(",","",worldometer$TotalDeaths))
  worldometer$TotalCases <- as.numeric(gsub(",","",worldometer$TotalCases))
  worldometer$NewDeaths <- as.numeric(gsub(",","",worldometer$NewDeaths))
  worldometer$NewCases <- as.numeric(gsub(",","",worldometer$NewCases))
  worldometer$TotalRecovered <- as.numeric(gsub(",","",worldometer$TotalRecovered))
  worldometer$ActiveCases <- as.numeric(gsub(",","",worldometer$ActiveCases))
  worldometer$`Serious,Critical` <- as.numeric(gsub(",","",worldometer$`Serious,Critical`))
  worldometer$`Tot Cases/1M pop` <<- as.numeric(gsub(",","",worldometer$`Tot Cases/1M pop`))
  # _________________________________ Worldometer Data _________________________________

  
  #_____________________________ Scrape financial data ______________________________________
  sp500_url <- 'https://za.investing.com/indices/us-spx-500-futures-historical-data'
  sp500 <<- read_html(sp500_url) %>% html_node(xpath='//*[@id="js-main-container"]/section[2]/div/section[2]/section[2]/div[1]/div/table') %>% html_table(fill = T)
  
  sa40_url <- 'https://za.investing.com/indices/south-africa-40-futures-historical-data'
  sa40 <<- read_html(sa40_url) %>% html_node(xpath='//*[@id="js-main-container"]/section[2]/div/section[2]/section[2]/div[1]/div/table') %>% html_table(fill = T)
  
  nasdaq_url <- 'https://za.investing.com/indices/nq-100-futures-historical-data'
  nasdaq <<- read_html(nasdaq_url) %>% html_node(xpath='//*[@id="js-main-container"]/section[2]/div/section[2]/section[2]/div[1]/div/table') %>% html_table(fill = T)
  
  london_url <- 'https://za.investing.com/equities/london-stock-exchange-historical-data'
  london <<- read_html(london_url) %>% html_node(xpath='//*[@id="js-main-container"]/section[2]/div/section[2]/section[2]/div[1]/div/table') %>% html_table(fill = T)
  
  nyse_url <- 'https://za.investing.com/indices/nyse-composite-historical-data'
  nyse <<- read_html(nyse_url) %>% html_node(xpath='//*[@id="js-main-container"]/section[2]/div/section[2]/section[2]/div[1]/div/table') %>% html_table(fill = T)
  
  ftse_url <- 'https://za.investing.com/indices/uk-100-historical-data'
  ftse <<- read_html(ftse_url) %>% html_node(xpath='//*[@id="js-main-container"]/section[2]/div/section[2]/section[2]/div[1]/div/table') %>% html_table(fill = T)
  
  hk50_url <- 'https://za.investing.com/indices/hang-sen-40-historical-data'
  hk50 <<- read_html(hk50_url) %>% html_node(xpath='//*[@id="js-main-container"]/section[2]/div/section[2]/section[2]/div[1]/div/table') %>% html_table(fill = T)
  
  gold_url <- 'https://za.investing.com/commodities/gold-historical-data'
  gold <<- read_html(gold_url) %>% html_node(xpath='//*[@id="js-main-container"]/section[2]/div/section[2]/section[2]/div[1]/div/table') %>% html_table(fill = T)
  
  zar_url <- 'https://za.investing.com/currencies/usd-zar-historical-data'
  zar <<- read_html(zar_url) %>% html_node(xpath='//*[@id="js-main-container"]/section[1]/div/section[2]/section[2]/div[1]/div/table') %>% html_table(fill = T)
  
  btc_url <- 'https://za.investing.com/crypto/bitcoin/btc-usd-historical-data'
  btc <<- read_html(btc_url) %>% html_node(xpath= '//*[@id="curr_table"]') %>% html_table(fill = T)
  #_____________________________ Scrape financial data ______________________________________


  
  
  # _________________________________ World Map Data _________________________________
  data("World")
  
  # clean case data
  case_data <- n_cases$global %>% group_by(country) %>% 
    summarise(cases=max(cum_confirm),
              cum_heal=max(cum_heal),
              cum_dead=max(cum_dead)) %>%
    mutate(name=factor(country))
  
  world <<- merge(World, case_data, by='name')                           # merge case data
  world <<- merge(world, med_age, by='name')                             # merge median age data 
  world <<- merge(world, global_population, by='name', all.x=TRUE)       # add global population data 
  
  worldometer$name = worldometer$`Country,Other`
  world2 <<- merge(world, worldometer, by='name')
  
}


configure_workspace()
get_data()
# ___________________________________ Install Dependencies & Curate Data ___________________________________



# ___________________________________________ Graphics Functions ___________________________________________

active_ratio_donut_graph <- function(worldometer, country_) {
  # Circular Graphic: Case Distribution
  
  
  x <- filter(worldometer, `Country,Other`==country_)                        # filter data  
   
  data <- data.frame(country=country_,                                       # Create data
                     category=c("Active", "Deaths", "Recovered"), 
                     count=c(as.numeric(sub(',', '',x$ActiveCases)), 
                             as.numeric(sub(',', '',x$TotalDeaths)),
                             as.numeric(sub(',', '',x$TotalRecovered))))
  
  data$fraction <- data$count / sum(data$count)                             # Compute percentages
  data$ymax <- cumsum(data$fraction)                                        # Compute the cumulative percentages (top of each rectangle)
  data$ymin <- c(0, head(data$ymax, n=-1))                                  # Compute the bottom of each rectangle
  data$labelPosition <- (data$ymax + data$ymin) / 2                         # Compute label position
  data$label <- paste0(data$category, "\n", data$count)                     # Compute a good label
  
  # Make the plot
  ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
    geom_rect() +
    geom_text_repel(x=1, aes(y=labelPosition, label=label, color=category), size=6) +
    # geom_text() + # x here controls label position (inner / outer)
    scale_fill_brewer(palette=3) +
    scale_color_brewer(palette=3) +
    coord_polar(theta="y") +
    xlim(c(-1, 4)) +
    theme_void() +
    theme(legend.position = "none") +
    labs(title = paste("Covid-19", data$country, "Summary")) +
    theme(plot.title = element_text(hjust = 0.5, size = 18, colour = 'darkgrey'))
}

effectiveness_of_response_graph <- function(n_cases, country_) {
  # Growth in Case Diagnostics
  
  x <- filter(n_cases$global, country==country_) 
  x$cum_open <- x$cum_confirm - x$cum_heal - x$cum_dead
  
  data <- data.frame()
  
  for (i in 1:nrow(x)) {
    # for each time step (row)
    d <- rbind(
      data.frame(time=x$time[i], country=x$country[i], group='cum_heal', count=x$cum_heal[i]),
      data.frame(time=x$time[i], country=x$country[i], group='cum_dead', count=x$cum_dead[i]),
      data.frame(time=x$time[i], country=x$country[i], group='cum_open', count=x$cum_open[i]))
    data <- rbind(data,d)
  }
  
  data %>%
    ggplot(aes(x=time, y=count, fill=group)) + 
    geom_area(colour="grey", size=.2, alpha=.9) +
    scale_fill_brewer(palette="Blues",
                      name="Cases",
                      breaks=c("cum_heal", "cum_dead", "cum_open"),
                      labels=c("Recovered", "Deaths", "Active")) +
    theme_minimal() +
    ggtitle(paste('Effectiveness of Response:', country_)) + 
    xlab('Date') +
    ylab('Cases') 
}

deaths_per_day_graph <- function(n_cases, country_) {
  # Deaths Per Day
  
  x <- n_cases$global[n_cases$global$country==country_,]
  x <- x[!is.na(x$country),]
  
  d <- c(0)
  for (i in 2:length(x$cum_dead)) d <- c(d, x$cum_dead[i]-x$cum_dead[i-1])
  
  x$deaths_per_day <- d
  
  ggplot(x, aes(x=time, y=deaths_per_day)) + 
    geom_point(size=1, col='darkred') +
    geom_segment(aes(x=time, xend=time, y=0, yend=deaths_per_day),  col='darkred') +
    ggtitle(paste('Deaths per day in', country_)) +
    ylab('Deaths') + xlab('Date') +
    theme_minimal()
}


# ___________________________________________ Graphics Functions ___________________________________________



# ___________________________________________ Themes  ___________________________________________
colour_cases <- '#1f77b4'
colour_active <- 'lightblue'
colour_recovered <- 'darkgreen'
colour_dead <- 'darkred'

```



South Africa
=======================================================================
Row
-----------------------------------------------------------------------

### cases {.value-box}

```{r}

# no. confirmed 
c <- as.numeric(worldometer[worldometer$`Country,Other`=='South Africa',]$TotalCases)

# no. deaths
d <- as.numeric(worldometer[worldometer$`Country,Other`=='South Africa',]$TotalDeaths)
d[is.na(d)]=0

# no. tests
t <- as.numeric(covid_sa$Agtests)
t[is.na(t)] <- 0
t <- max(t)

# no. recovered
r <- as.numeric(worldometer[worldometer$`Country,Other`=='South Africa',]$TotalRecovered)





valueBox(value = paste(format(c, big.mark = ","), "", sep = " "), 
         caption = "Total Confirmed Cases", 
         icon = "fas fa-user-md", 
         color = colour_cases)

```

### active {.value-box}

```{r}

valueBox(value = paste(format((c-d-r), big.mark = ","), "", sep = " "), 
         caption = "Active", 
         icon = "fas fa-ambulance", 
         color = colour_active)

```

### recovered {.value-box}

```{r}


valueBox(value = paste(format(r, big.mark = ","), "", sep = " "), 
         caption = "Recovered", 
         icon = "fas fa-heartbeat", 
         color = colour_recovered)

```


### deaths {.value-box}

```{r}

valueBox(value = paste(format(d, big.mark = ","), "", sep = " "), 
         caption = "Fatalities", 
         icon = "fas fa-feather", 
         color = colour_dead)

```

Row
-----------------------------------------------------------------------

### {data-width=200}

```{r}



tc <- as.numeric(sub(',', '', worldometer[worldometer$`Country,Other`=='Total:',]$TotalCases))
tr <- as.numeric(sub(',', '', worldometer[worldometer$`Country,Other`=='Total:',]$TotalRecovered))
td <- as.numeric(sub(',', '', worldometer[worldometer$`Country,Other`=='Total:',]$TotalDeaths))

x <- data.frame(values=c(tc,tr,td),
                group=c('Total','Recovered','Deaths'))

ggplot(x, aes(x=group, y=values, fill=factor(values))) + 
  geom_bar(stat='identity') + theme_minimal() + ggtitle('Global Cases') +
  xlab('') +
  scale_fill_manual(values = c(RColorBrewer::brewer.pal(3, 'Blues'))) + 
  theme(legend.title = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())



```



### {data-width=400}

```{r}


tmap_leaflet(
  tm_shape(world2) +
    tm_layout(title='Understand the World - Take a closer look') + 
    tm_borders(alpha=0.3) + 
    tm_fill('TotalCases', title='Cases', palette=c(RColorBrewer::brewer.pal(9,'Blues')[5:9]),
            legend.show = F,
            breaks=c(0,50,100,200,500,1000,5000,10000,100000),
            popup.vars=c('cases'='TotalCases', 'cured'='TotalRecovered', 'fatalities'='TotalDeaths', 
                         'median age'='median_age', 'population'='pop_char'))
)


```



Row
-----------------------------------------------------------------------

### {}
```{r}

# SA over time
x <- n_cases$global[n_cases$global$country=='South Africa',][c('time','cum_confirm')]

x <- x[!is.na(x$cum_confirm),]
x <- rbind(x, data.frame(time=Sys.Date(),
           cum_confirm=as.numeric(worldometer[worldometer$`Country,Other`=='South Africa',]$TotalCases)))


ggplot(x, aes(time, cum_confirm, fill='blue')) +
  geom_point(shape = 21, colour="steelblue", fill="white", size=2, stroke=1) +
  #geom_segment(aes(x=time, xend=time, y=0, yend=cum_confirm),  size=0.5, col='steelblue') + 
  geom_line(color='steelblue', size=0.5) + ylab('Cases') + xlab('') + ggtitle('Growth in Cases in SA') + 
  theme_minimal()

```




### Covid19 Cases {}


```{r}

# Graph of SA
# tmap_leaflet(
#   tm_shape(south_africa) +
#           tm_layout(title='Confirmed Cases in SA') +
#           tm_borders(alpha=0.3) +
#           tm_fill('Cases', title='Confirmed Cases', palette=c(RColorBrewer::brewer.pal(10, 'OrRd')[2:7]),
#                   breaks=c(0,10,20,50,100,200),
#                   popup.vars=c('cases'="Cases", "population_2", 'pop density'="density")))





library(randomcoloR)





sa_data <- cbind(sa_cases, data.frame(country=c('Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo', 'Mpumalanga',
                                                'North West', 'Northern Cape','Western Cape')))



circular_data_prep <- function(data) {
  data$fraction <- data$Cases / sum(data$Cases)                             # Compute percentages
  data$ymax <- cumsum(data$fraction)                                        # Compute the cumulative percentages (top of each rectangle)
  data$ymin <- c(0, head(data$ymax, n=-1))                                  # Compute the bottom of each rectangle
  data$labelPosition <- (data$ymax + data$ymin) / 2                         # Compute label position
  data$label <- paste0(data$country, "\n", data$Cases)                     # Compute a good label
  
  data
}

sa_data <- circular_data_prep(sa_data)

sa_data <- sa_data %>% 
arrange(desc(Cases)) %>% mutate(lab.ypos=cumsum(fraction) - 0.5*fraction)


ggplot(sa_data, aes(x = 2, y = fraction, fill = country)) +
  geom_bar(stat = "identity", color = "white") +
  coord_polar(theta = "y", start=1) +
  # geom_text(aes(y = lab.ypos, label = Cases), color = "white")+
  #scale_fill_manual(values = c(RColorBrewer::brewer.pal(9, 'Spectral'))) +
  scale_fill_manual(values=c(randomcoloR::randomColor(9))) +
  ggtitle('Covid19 Cases per Province') + 
  theme_void() +
  xlim(0.5, 2.5)





```




















Country Analysis
=======================================================================


Input {.sidebar}
-----------------------------------------------------------------------

Compare countries. Data updated once daily.

```{r input}
countries <- read_csv('data/country_names.csv')$x

selectInput('con_a', 'Select a Country', selected='China', countries)


```


Row {width=600}
-----------------------------------------------------------------------



### Deaths per Day {width=400}
```{r}
renderPlot(deaths_per_day_graph(n_cases, input$con_a))
```


### Situation Update {width=200}
```{r}
renderPlot(active_ratio_donut_graph(worldometer, input$con_a))
```



Row {width=600}
-----------------------------------------------------------------------

### {data-width=400}
```{r}
renderPlot(effectiveness_of_response_graph(n_cases, input$con_a))
```


### {data-width=200}
```{r}

age_dist <- read_csv('data/age_dist.csv')
Age_distribution_plot <- function(country_, age_dist=age_dist) {
  
  # create data
  x <- age_dist[age_dist$`Country Name`==country_,]            
  x <- data.frame(rbind(rbind(
      cbind(value=x$`00-14`, group=1), 
      cbind(value=x$`15-64`, group=2)
    ),
    cbind(value=x$`65+`, group=3)))
  
  
  ggplot(x, aes(x=group, y=value)) +
    geom_point(size=3, col=colour_cases) +
    geom_segment(aes(x=group, xend=group, y=0, yend=value), col=colour_cases) +
    stat_smooth(geom='line', col=colour_cases) +
    theme_minimal() + xlab('Age') + ylab('Percent of Population') + ggtitle(paste('Age Distribution of', country_)) +
    scale_x_continuous(
      breaks=c(1,2,3), labels=c('0-14', '15-64', '65+'))
  
}

renderPlot(Age_distribution_plot(input$con_a,age_dist))

```


















Global Economy
=======================================================================




Input {.sidebar}
-----------------------------------------------------------------------

```{r}

# create one dataset
sp500$indx <- 'sp500'
sp500 <- sp500[c('Date', 'Price', 'indx')]
btc$indx <- 'btc'
btc <- btc[c('Date', 'Price', 'indx')]
ftse$indx <- 'ftse'
ftse <- ftse[c('Date', 'Price', 'indx')]
gold$indx <- 'gold'
gold <- gold[c('Date', 'Price', 'indx')]
hk50$indx <- 'hk50'
hk50 <- hk50[c('Date', 'Price', 'indx')]
london$indx <- 'london'
london <- london[c('Date', 'Price', 'indx')]
nasdaq$indx <- 'nasdaq'
nasdaq <- nasdaq[c('Date', 'Price', 'indx')]
nyse$indx <- 'nyse'
nyse <- nyse[c('Date', 'Price', 'indx')]
sa40$indx <- 'sa40'
sa40 <- sa40[c('Date', 'Price', 'indx')]
zar$indx <- 'zar'
zar <- zar[c('Date', 'Price', 'indx')]
data <- data.frame(rbind(sp500,btc,ftse,gold,hk50,london,nasdaq,nyse,sa40,zar))


data$Date <- as.Date(data$Date, format='%b %d, %Y')                              # convert to date class
data$Price <- as.numeric(sub(',', '', data$Price))                               # convert to double

# compute standarize prices
data <- data %>% group_by(indx) %>% mutate(std_price = (Price-min(Price))/max(Price))


selectizeInput('equity_data', 'Select Markets', selected='sa40', choices=c(unique(data$indx)), multiple=T)

```


Row {width=600}
-----------------------------------------------------------------------


### Global Financial Health {data-width=350}
```{r}


financial_graph <- function(input_var_) {
    data[data$indx==c(input_var_),] %>%
    ggplot(aes(x=Date, y=std_price, fill=indx)) + ggtitle('Global Markets') + 
    ylab('Price') + theme(axis.ticks.y = element_blank(), axis.text.y = element_blank()) +
    geom_line(aes(x=Date, y=std_price, col=indx)) + theme_minimal() 
 

}

renderPlot(financial_graph(input$equity_data))


```



### Whats Important to You? {data-width=250}

What do you want to see next?

Connect with us, share your ideas:

Zach: 084 496 8779
Keagan: 083 642 3300










